version: "3"
services:
  fpm1:
    restart: "no"
    build: ./build/fpm
    volumes:
      - ./data/www:/var/www/html
    environment:
      APP_ENV: development
      APP_DEBUG: 1
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
    links:
      - db
      - memcached
  fpm2:
    restart: "no"
    build: ./build/fpm
    volumes:
      - ./data/www:/var/www/html
    environment:
      APP_ENV: development
      APP_DEBUG: 1
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
    links:
      - db
      - memcached
  fpm3:
    restart: "no"
    build: ./build/fpm
    volumes:
      - ./data/www:/var/www/html
    environment:
      APP_ENV: development
      APP_DEBUG: 1
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
    links:
      - db
      - memcached
  nginx:
    restart: "no"
    build: ./build/nginx
    volumes:
      - ./data/www:/var/www/html
      - ./data/www/public:/var/www/html/public
      - ./data/nginx/log:/var/log/nginx
    links:
      - fpm1
      - fpm2
      - fpm3
    ports:
      - "50050:80"
  db:
    restart: "no"
    build: ./build/db
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: project_1024
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project_1024
  redis:
    restart: "no"
    image: redis:latest
    volumes:
      - ./data/redis:/data
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    restart: always